# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:
    # Set options, as documented at https://datatables.net/reference/option/
    options:
        lengthMenu: [[10, 25, 50, 100, 250, 500, -1], [10, 25, 50, 100, 250, 500, 'All']]
        pageLength: 10
        searching: true
        dom: "<'row' <'col-sm-6'l><'col-sm-6 text-end'f>><'row' <'col-sm-12' tr>><'row' <'col-sm-12 text-start'i>> <'row' <'col-sm-12 text-center'p>>"
        pagingType: simple_numbers

    template_parameters:
        # Example classes to integrate nicely with Bootstrap 5.x
        className: 'table table-striped table-bordered table-hover data-table'

    # You can for example override this to "tables" to keep the translation domains separated nicely
    translation_domain: 'messages'
    language_from_cdn: false